### ISSUE TITLE
Example with OZ / imports

### ISSUE THREAD

**Issue by pegahcarter** [Tenderly/tenderly-sdk#68]
Hello,

Would you be able to provide an example of verifying a contract that has multiple imports, including some OpenZeppelin imports?

**Comment by dule-git** [comment]
Hello 👋🏽

We've released a new version of the SDK (`0.1.9`) where we included the examples of contract verification that you asked for. There is also an example on how to verify a contract that has libraries. 📚

You can find all of the contract verification examples [here](https://github.com/Tenderly/tenderly-sdk/tree/master/examples/contractVerification). Happy coding 🚀
