### ISSUE TITLE
SimulationCallArguments value type should be string not number

### ISSUE THREAD

**Issue by marcusmolchany** [Tenderly/tenderly-sdk#90]
https://github.com/Tenderly/tenderly-sdk/blob/master/lib/executors/Simulator.types.ts#L57

should this `value` type be `string`? wei values can overflow as `number`s in js.

(i can make this pr if we agree on the change)

**Comment by maleksandar** [comment]
Hi @marcusmolchany! First of all, sorry for the late reply! 

It does seem that `string` or `BigInt` would be a better option here. We can add this to our own backlog and address this in the coming weeks, but if you have a PR ready, you are more than welcome to submit it! 🙌

Thank you for catching this and for making Tenderly SDK a more complete tool, We really appreciate it! 🙏

**Comment by maleksandar** [comment]
Hi, @marcusmolchany! We had some issues with running the tests on our CI. We resolved that and the tests are passing, so I have merged your changes! Thanks for the PR, and thank you for your patience as well!

**Comment by marcusmolchany** [comment]
thank you @maleksandar!
